[functions.generate-meal-plan]
entrypoint = "./functions/generate-meal-plan/index.ts"
verify_jwt = true

[functions.invite-member]
entrypoint = "./functions/invite-member/index.ts"
verify_jwt = true

# Add this new section for the shopping list function
[functions.generate-shopping-list]
entrypoint = "./functions/generate-shopping-list/index.ts"
verify_jwt = true