# My functions are defined here.
# I've removed the 'sign-up-with-profile' function as it's no longer needed.
[functions.generate-meal-plan]
entrypoint = "./functions/generate-meal-plan/index.ts"
verify_jwt = true

[functions.invite-member]
entrypoint = "./functions/invite-member/index.ts"
verify_jwt = true

[functions.generate-shopping-list]
entrypoint = "./functions/generate-shopping-list/index.ts"
verify_jwt = true